Hw02 unpack string
mrvin/hw-otus-go pull request #2
Opened 2020-09-09 13:42 UTC by mrvin

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-09 17:24 UTC, kulti approved these changes, later dismissed
Хорошее понятно решение через стейт-машину 👍 

Код получился местами грязноватый. Если хотите 10 баллов, то предложения по улучшению кода в дискашенах.

Пока принимаю ДЗ на 9 из 10.

2020-09-09 17:24 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			startState(&state, ch)
Обычно обработчик стейта принимает текущий стейт и возвращает новый: `state = startState(state, ch)`. В таком случае получаются методы без побочных эффектов.

2020-09-09 17:24 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		if _, err := resultStr.WriteString(strings.Repeat(string(prevCh), num)); err != nil {
`Write` методы у стрингбилдера никогда не возвращают ошибку.

2020-09-09 17:24 UTC, kulti commented on hw02_unpack_string/unpack.go
> +func digitState(state *state, ch rune) {
digitState полностью дублирует startState и это неспроста. Входящую строку можно разбить на несколько подстрок, каждую из которых можно обработать этой стейт-машиной. `a4bc2d5e` -> `a4`+`bc2`+`d5`+`e`. Предлагаю избавиться от стейта digit.

2020-09-14 13:08 UTC, mrvin commented on hw02_unpack_string/unpack.go
> +func digitState(state *state, ch rune) {
@kulti 
Спасибо за ревью кода. Замечания исправил. Проверьте, пожалуйста.

2020-09-14 17:46 UTC, kulti requested changes
Стейт машина стала проще, но появился ненужный цикл и вкралась ошибка.

2020-09-14 17:46 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	for _, substr := range splitStr {
Не нужно разбивать строку на кусочки.

Я говорил о том, что когда алгоритм идет о строке a4bc2d5e и доходит до 4, то потом он, можно считать начинает распаковывать новую строку bc2d5e тем же алгоритмом, начиная со стейта start.

printState так и делает. SplitAfterDigit  и этот внешний цикл не нужны.

2020-09-14 17:46 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		if state != start {
А если backSlash? Добавьте, пожалуйста, тест на этот случай.

2020-09-15 16:26 UTC, mrvin commented on hw02_unpack_string/unpack.go
> +	for _, substr := range splitStr {
Убрал функцю SplitAfterDigit и лишний цикл.

2020-09-15 16:28 UTC, mrvin commented on hw02_unpack_string/unpack.go
> +		if state != start {
@kulti
Добавил тест и исправил ошибку. Проверьте, пожалуйста.

2020-09-15 16:40 UTC, kulti submitted a review, later dismissed
Куд улучшен, ошибки починены. Поднял баллы до 10.

2020-09-15 16:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		switch state { //nolint:exhaustive // Warns about missing cases in switch of type state: exit
Здорово, что не просто отключили линтер, но и объяснили почему.

Вроде, можно не возвращать ошибку из *State() методов и добавить обработку стейта exit. Но и без этого уже все отлично.

2020-09-15 17:41 UTC, mrvin commented on hw02_unpack_string/unpack.go
> +		switch state { //nolint:exhaustive // Warns about missing cases in switch of type state: exit
@kulti
Исправил.

2020-09-15 17:47 UTC, kulti approved these changes

2020-09-15 17:52 UTC, merged